// GENERADO: precarga de países para el template de Resultados electorales (ids = claves de apps/output/src/lib/electionMaps.json).
export interface ElectionRegion { id: string; name: string }
export interface ElectionCountry { id: string; name: string; regionLabel: string; regions: ElectionRegion[] }
export const ELECTION_COUNTRIES: ElectionCountry[] = [
  { id: "ar", name: "Argentina", regionLabel: "Provincias", regions: [{ id: "E", name: "Entre Ríos" }, { id: "A", name: "Salta" }, { id: "Y", name: "Jujuy" }, { id: "P", name: "Formosa" }, { id: "N", name: "Misiones" }, { id: "H", name: "Chaco" }, { id: "W", name: "Corrientes" }, { id: "K", name: "Catamarca" }, { id: "F", name: "La Rioja" }, { id: "J", name: "San Juan" }, { id: "M", name: "Mendoza" }, { id: "Q", name: "Neuquén" }, { id: "U", name: "Chubut" }, { id: "R", name: "Río Negro" }, { id: "Z", name: "Santa Cruz" }, { id: "V", name: "Tierra del Fuego" }, { id: "B", name: "Buenos Aires" }, { id: "C", name: "Ciudad de Buenos Aires" }, { id: "S", name: "Santa Fe" }, { id: "T", name: "Tucumán" }, { id: "G", name: "Santiago del Estero" }, { id: "D", name: "San Luis" }, { id: "L", name: "La Pampa" }, { id: "X", name: "Córdoba" }] },
  { id: "br", name: "Brasil", regionLabel: "Estados", regions: [{ id: "RS", name: "Rio Grande do Sul" }, { id: "RR", name: "Roraima" }, { id: "PA", name: "Pará" }, { id: "AC", name: "Acre" }, { id: "AP", name: "Amapá" }, { id: "MS", name: "Mato Grosso do Sul" }, { id: "PR", name: "Paraná" }, { id: "SC", name: "Santa Catarina" }, { id: "AM", name: "Amazonas" }, { id: "RO", name: "Rondônia" }, { id: "MT", name: "Mato Grosso" }, { id: "MA", name: "Maranhão" }, { id: "PI", name: "Piauí" }, { id: "CE", name: "Ceará" }, { id: "RN", name: "Rio Grande do Norte" }, { id: "PB", name: "Paraíba" }, { id: "PE", name: "Pernambuco" }, { id: "AL", name: "Alagoas" }, { id: "SE", name: "Sergipe" }, { id: "BA", name: "Bahia" }, { id: "ES", name: "Espírito Santo" }, { id: "RJ", name: "Rio de Janeiro" }, { id: "SP", name: "São Paulo" }, { id: "GO", name: "Goiás" }, { id: "DF", name: "Distrito Federal" }, { id: "MG", name: "Minas Gerais" }, { id: "TO", name: "Tocantins" }] },
  { id: "us", name: "Estados Unidos", regionLabel: "Estados", regions: [{ id: "WA", name: "Washington" }, { id: "ID", name: "Idaho" }, { id: "MT", name: "Montana" }, { id: "ND", name: "Dakota del Norte" }, { id: "MN", name: "Minnesota" }, { id: "MI", name: "Míchigan" }, { id: "OH", name: "Ohio" }, { id: "PA", name: "Pensilvania" }, { id: "NY", name: "Nueva York" }, { id: "VT", name: "Vermont" }, { id: "NH", name: "Nuevo Hampshire" }, { id: "ME", name: "Maine" }, { id: "AZ", name: "Arizona" }, { id: "CA", name: "California" }, { id: "NM", name: "Nuevo México" }, { id: "TX", name: "Texas" }, { id: "AK", name: "Alaska" }, { id: "LA", name: "Luisiana" }, { id: "MS", name: "Misisipi" }, { id: "AL", name: "Alabama" }, { id: "FL", name: "Florida" }, { id: "GA", name: "Georgia" }, { id: "SC", name: "Carolina del Sur" }, { id: "NC", name: "Carolina del Norte" }, { id: "VA", name: "Virginia" }, { id: "DC", name: "Washington D. C." }, { id: "MD", name: "Maryland" }, { id: "DE", name: "Delaware" }, { id: "NJ", name: "Nueva Jersey" }, { id: "CT", name: "Connecticut" }, { id: "RI", name: "Rhode Island" }, { id: "MA", name: "Massachusetts" }, { id: "OR", name: "Oregón" }, { id: "HI", name: "Hawái" }, { id: "UT", name: "Utah" }, { id: "WY", name: "Wyoming" }, { id: "NV", name: "Nevada" }, { id: "CO", name: "Colorado" }, { id: "SD", name: "Dakota del Sur" }, { id: "NE", name: "Nebraska" }, { id: "KS", name: "Kansas" }, { id: "OK", name: "Oklahoma" }, { id: "IA", name: "Iowa" }, { id: "MO", name: "Misuri" }, { id: "WI", name: "Wisconsin" }, { id: "IL", name: "Illinois" }, { id: "KY", name: "Kentucky" }, { id: "AR", name: "Arkansas" }, { id: "TN", name: "Tennessee" }, { id: "WV", name: "Virginia Occidental" }, { id: "IN", name: "Indiana" }] },
  { id: "fr", name: "Francia", regionLabel: "Regiones", regions: [{ id: "HDF", name: "Hauts-de-France" }, { id: "GES", name: "Grand Est" }, { id: "PAC", name: "Provence-Alpes-Côte-d'Azur" }, { id: "ARA", name: "Auvergne-Rhône-Alpes" }, { id: "NAQ", name: "Nouvelle-Aquitaine" }, { id: "OCC", name: "Occitanie" }, { id: "BFC", name: "Bourgogne-Franche-Comté" }, { id: "PDL", name: "Pays de la Loire" }, { id: "BRE", name: "Bretagne" }, { id: "NOR", name: "Normandie" }, { id: "COR", name: "Corse" }, { id: "CVL", name: "Centre-Val de Loire" }, { id: "IDF", name: "Île-de-France" }] },
  { id: "sv", name: "El Salvador", regionLabel: "Departamentos", regions: [{ id: "AH", name: "Ahuachapán" }, { id: "SA", name: "Santa Ana" }, { id: "CH", name: "Chalatenango" }, { id: "CA", name: "Cabañas" }, { id: "MO", name: "Morazán" }, { id: "SM", name: "San Miguel" }, { id: "UN", name: "La Unión" }, { id: "SO", name: "Sonsonate" }, { id: "LI", name: "La Libertad" }, { id: "PA", name: "La Paz" }, { id: "SV", name: "San Vicente" }, { id: "US", name: "Usulután" }, { id: "CU", name: "Cuscatlán" }, { id: "SS", name: "San Salvador" }] },
];
